POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJ1ZGQiLCJpZCI6IjYzNjE4Yjc2ODc3ODg2NWE2OGQ1ZGU0NyIsImlhdCI6MTY2NzMzNzIxNH0.TaRgsoUUoneY9UU_vhwa9MDyauzAUUaAG-ZudPuUHzc
 
{
    "title": "Check it out now the funk show brother",
    "author": "90s music?",
    "url": "www.bennett.org",
    "likes": 0,
    "user": "63618b658778865a68d5de43"
}  

  